# Generated by Django 2.1.4 on 2018-12-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('Email_id', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('message', models.CharField(max_length=220)),
            ],
        ),
    ]
