# Generated by Django 2.1.4 on 2018-12-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='display',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Contact_no', models.IntegerField()),
                ('room_type', models.CharField(max_length=10)),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
                ('Address', models.CharField(max_length=20)),
                ('Cust_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Total_amount', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
