# Generated by Django 2.1.4 on 2018-12-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbapp', '0003_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=20)),
                ('Room_no', models.IntegerField()),
                ('Cust_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='display',
            name='room_type',
            field=models.CharField(max_length=20),
        ),
    ]
