# Generated by Django 2.1.4 on 2018-12-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbapp', '0004_auto_20181216_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('Room_type', models.CharField(max_length=20)),
                ('Check_in', models.DateField()),
                ('Check_out', models.DateField()),
                ('Contact_no', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('Card_no', models.IntegerField()),
                ('Card_type', models.CharField(max_length=20)),
            ],
        ),
    ]
