# Generated by Django 2.1.4 on 2018-12-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hbapp', '0005_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Fname',
            new_name='Fullname',
        ),
    ]
