# Generated by Django 2.1.4 on 2018-12-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbapp', '0006_auto_20181216_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='display',
        ),
        migrations.AddField(
            model_name='payment',
            name='Total_amount',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
