# Generated by Django 2.1.4 on 2018-12-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbapp', '0008_auto_20181216_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Cust_Id',
        ),
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
